spring.application.name=twitter-clone

spring.datasource.url=jdbc:postgresql://localhost:5432/twitter_clone
spring.datasource.username=postgres
spring.datasource.password=jeevi08

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080